export const XP_CONFIG = {
  BASE_XP: 50,
  LEVEL_SCALING: 0.1,
  DIFFICULTY_SCALING: 0.2,
  STAT_BONUS_SCALING: 0.05,
  LEVEL_THRESHOLD: 1000, // XP needed for level up
  MAX_STAT_VALUE: 10,
  MIN_STAT_VALUE: 1
};

export const QUEST_CONFIG = {
  MAX_ACTIVE_QUESTS: 5,
  MIN_QUEST_DIFFICULTY: 1,
  MAX_QUEST_DIFFICULTY: 5,
  STAT_REQUIREMENT_THRESHOLD: 0.7 // 70% of requirements must be meetable
};
